let collegeList = [
  {
    name: "Arizona State University",
    town: "Tempe, AZ",
    region: "West",
    sat: 1245,
    act: 26,
    gpa: 3.56,
    size: 63124,
    setting: "Urban",
    type: "Public",
    link: "https://www.asu.edu/",
  },
  {
    name: "Auburn University",
    town: "Auburn, AL",
    region: "South",
    sat: 1235,
    act: 28,
    gpa: 3.79,
    size: 24505,
    setting: "Suburban",
    type: "Public",
    link: "https://www.auburn.edu/",
  },
  {
    name: "Binghamton University",
    town: "Binghamton, NY",
    region: "Northeast",
    sat: 1375,
    act: 30,
    gpa: 3.81,
    size: 14333,
    setting: "Suburban",
    type: "Public",
    link: "https://www.binghamton.edu/",
  },
  {
    name: "Boston College",
    town: "Chestnut Hill, MA",
    region: "Northeast",
    sat: 1420,
    act: 33,
    gpa: 3.71,
    size: 9445,
    setting: "Suburban",
    type: "Private",
    link: "https://www.bc.edu/",
  },
  {
    name: "Boston University",
    town: "Boston, MA",
    region: "Northeast",
    sat: 1420,
    act: 32,
    gpa: 3.66,
    size: 16872,
    setting: "Urban",
    type: "Private",
    link: "https://www.bu.edu/",
  },
  {
    name: "Brandeis University",
    town: "Waltham, MA",
    region: "Northeast",
    sat: 1400,
    act: 31,
    gpa: 3.8,
    size: 3493,
    setting: "Suburban",
    type: "Private",
    link: "https://www.brandeis.edu/",
  },
  {
    name: "Brown University",
    town: "Providence, RI",
    region: "Northeast",
    sat: 1485,
    act: 34,
    gpa: 3.94,
    size: 6792,
    setting: "Urban",
    type: "Private",
    link: "https://www.brown.edu/",
  },
  {
    name: "California Institute of Technology",
    town: "Pasadena, CA",
    region: "West",
    sat: 1545,
    act: 36,
    gpa: 3.97,
    size: 901,
    setting: "Suburban",
    type: "Private",
    link: "https://www.caltech.edu/",
  },
  {
    name: "California State University Fresno",
    town: "Fresno, CA",
    region: "West",
    sat: 1010,
    act: 19,
    gpa: 3.45,
    size: 22611,
    setting: "Urban",
    type: "Public",
    link: "https://www.fresnostate.edu/",
  },
  {
    name: "Carnegie Mellon University",
    town: "Pittsburgh, PA",
    region: "Northeast",
    sat: 1510,
    act: 34,
    gpa: 3.8,
    size: 7073,
    setting: "Urban",
    type: "Private",
    link: "https://www.cmu.edu/",
  },
  {
    name: "Case Western University",
    town: "Cleveland, OH",
    region: "Midwest",
    sat: 1435,
    act: 32,
    gpa: 3.86,
    size: 5433,
    setting: "Urban",
    type: "Private",
    link: "https://case.edu/",
  },
  {
    name: "Clemson University",
    town: "Clemson, SC",
    region: "South",
    sat: 1310,
    act: 30,
    gpa: 3.86,
    size: 20868,
    setting: "Suburban",
    type: "Public",
    link: "http://www.clemson.edu/",
  },
  {
    name: "College of William and Mary",
    town: "Williamsburg, VA",
    region: "South",
    sat: 1415,
    act: 32,
    gpa: 3.86,
    size: 6236,
    setting: "Suburban",
    type: "Private",
    link: "https://www.wm.edu/",
  },
  {
    name: "Colorado School of Mines",
    town: "Golden, CO",
    region: "West",
    sat: 1360,
    act: 30,
    gpa: 3.81,
    size: 5216,
    setting: "Suburban",
    type: "Public",
    link: "https://www.mines.edu/",
  },
  {
    name: "Columbia University",
    town: "New York, NY",
    region: "Northeast",
    sat: 1505,
    act: 34,
    gpa: 3.91,
    size: 6170,
    setting: "Urban",
    type: "Private",
    link: "https://www.columbia.edu/",
  },
  {
    name: "Cornell University",
    town: "Ithaca, NY",
    region: "Northeast",
    sat: 1480,
    act: 34,
    gpa: 3.9,
    size: 14743,
    setting: "Suburban",
    type: "Private",
    link: "https://www.cornell.edu/",
  },
  {
    name: "Dartmouth College",
    town: "Hanover, NH",
    region: "Northeast",
    sat: 1500,
    act: 34,
    gpa: 3.9,
    size: 4170,
    setting: "Suburban",
    type: "Private",
    link: "https://dartmouth.edu/",
  },
  {
    name: "Duke University",
    town: "Durham, NC",
    region: "South",
    sat: 1510,
    act: 34,
    gpa: 3.94,
    size: 6717,
    setting: "Suburban",
    type: "Private",
    link: "https://duke.edu/",
  },
  {
    name: "Emory University",
    town: "Atlanta, GA",
    region: "South",
    sat: 1435,
    act: 33,
    gpa: 3.76,
    size: 7010,
    setting: "Urban",
    type: "Private",
    link: "https://www.emory.edu/",
  },
  {
    name: "Florida International University",
    town: "Miami, FL",
    region: "South",
    sat: 1195,
    act: 26,
    gpa: 3.81,
    size: 48664,
    setting: "Urban",
    type: "Public",
    link: "https://www.fiu.edu/",
  },
  {
    name: "Florida State University",
    town: "Tallahassee, FL",
    region: "South",
    sat: 1270,
    act: 28,
    gpa: 3.82,
    size: 32543,
    setting: "Urban",
    type: "Public",
    link: "https://www.fsu.edu/",
  },
  {
    name: "George Mason University",
    town: "Fairfax, VA",
    region: "South",
    sat: 1215,
    act: 27,
    gpa: 3.65,
    size: 37677,
    setting: "Suburban",
    type: "Public",
    link: "https://www.gmu.edu/",
  },
  {
    name: "Georgetown University",
    town: "Washington, D.C.",
    region: "South",
    sat: 1450,
    act: 33,
    gpa: 3.89,
    size: 7357,
    setting: "Urban",
    type: "Private",
    link: "https://www.georgetown.edu/",
  },
  {
    name: "Georgia Institute of Technology",
    town: "Atlanta, GA",
    region: "South",
    sat: 1465,
    act: 33,
    gpa: 3.9,
    size: 16561,
    setting: "Urban",
    type: "Public",
    link: "https://www.gatech.edu/",
  },
  {
    name: "Harvard University",
    town: "Cambridge, MA",
    region: "Northeast",
    sat: 1520,
    act: 34,
    gpa: 3.87,
    size: 5222,
    setting: "Urban",
    type: "Private",
    link: "https://www.harvard.edu/",
  },
  {
    name: "Indiana University Bloomington",
    town: "Bloomington, IN",
    region: "Midwest",
    sat: 1255,
    act: 28,
    gpa: 3.77,
    size: 32986,
    setting: "Urban",
    type: "Public",
    link: "https://www.indiana.edu/",
  },
  {
    name: "Iowa State University of Science and Technology",
    town: "Ames, IA",
    region: "Midwest",
    sat: 1220,
    act: 25,
    gpa: 3.64,
    size: 26846,
    setting: "Urban",
    type: "Public",
    link: "https://www.iastate.edu/",
  },
  {
    name: "Johns Hopkins University",
    town: "Baltimore, MD",
    region: "South",
    sat: 1505,
    act: 34,
    gpa: 3.86,
    size: 6331,
    setting: "Urban",
    type: "Private",
    link: "https://www.jhu.edu/",
  },
  {
    name: "Kansas State University",
    town: "Manhatan, KS",
    region: "Midwest",
    sat: 1160,
    act: 24,
    gpa: 3.63,
    size: 16257,
    setting: "Urban",
    type: "Public",
    link: "https://www.k-state.edu/",
  },
  {
    name: "Lehigh University",
    town: "Lehigh, PA",
    region: "Northeast",
    sat: 1365,
    act: 31,
    gpa: 3.81,
    size: 5203,
    setting: "Urban",
    type: "Private",
    link: "https://www.lehigh.edu/",
  },
  {
    name: "Louisiana State University Baton Rouge",
    town: "Baton Rouge, Louisiana",
    region: "South",
    sat: 1180,
    act: 26,
    gpa: 3.53,
    size: 27825,
    setting: "Urban",
    type: "Public",
    link: "https://www.lsu.edu/",
  },
  {
    name: "Massachusetts Institute of Technology",
    town: "Cambridge, MA",
    region: "Northeast",
    sat: 1535,
    act: 35,
    gpa: 3.96,
    size: 4361,
    setting: "Urban",
    type: "Private",
    link: "https://www.mit.edu/",
  },
  {
    name: "Miami University Oxford",
    town: "Miami, FL",
    region: "South",
    sat: 1310,
    act: 29,
    gpa: 3.76,
    size: 16522,
    setting: "Suburban",
    type: "Public",
    link: "https://miamioh.edu/",
  },
  {
    name: "Michigan State University",
    town: "East Lansing, Michigan",
    region: "Midwest",
    sat: 1210,
    act: 26,
    gpa: 3.75,
    size: 38491,
    setting: "Suburban",
    type: "Public",
    link: "https://msu.edu/",
  },
  {
    name: "New Jersey Institute of Technology",
    town: "Newark, NJ",
    region: "Northeast",
    sat: 1290,
    act: 27,
    gpa: 3.59,
    size: 11325,
    setting: "Urban",
    type: "Public",
    link: "https://www.njit.edu/",
  },
  {
    name: "New Mexico State University",
    town: "Las Cruces, NM",
    region: "West",
    sat: 1033,
    act: 21,
    gpa: 3.53,
    size: 11575,
    setting: "Urban",
    type: "Public",
    link: "https://nmsu.edu/",
  },
  {
    name: "New York University",
    town: "New York, NY",
    region: "Northeast",
    sat: 1440,
    act: 32,
    gpa: 3.69,
    size: 27444,
    setting: "Urban",
    type: "Private",
    link: "https://www.nyu.edu/",
  },
  {
    name: "North Carolina State University",
    town: "Raleigh, NC",
    region: "South",
    sat: 1335,
    act: 30,
    gpa: 3.76,
    size: 34015,
    setting: "Urban",
    type: "Public",
    link: "https://www.ncsu.edu/",
  },
  {
    name: "Northeastern University",
    town: "Boston, MA",
    region: "Northeast",
    sat: 1465,
    act: 34,
    gpa: 3.91,
    size: 15156,
    setting: "Urban",
    type: "Private",
    link: "https://www.northeastern.edu/",
  },
  {
    name: "Northwestern University",
    town: "Evanston, IL",
    region: "Midwest",
    sat: 1495,
    act: 34,
    gpa: 3.92,
    size: 8194,
    setting: "Suburban",
    type: "Private",
    link: "https://www.northwestern.edu/",
  },
  {
    name: "Oregon State University",
    town: "Corvallis, OR",
    region: "West",
    sat: 1195,
    act: 25,
    gpa: 3.69,
    size: 26644,
    setting: "Urban",
    type: "Public",
    link: "https://oregonstate.edu/",
  },
  {
    name: "Pepperdine University",
    town: "Malibu, CA",
    region: "West",
    sat: 1320,
    act: 29,
    gpa: 3.71,
    size: 3459,
    setting: "Suburban",
    type: "Private",
    link: "https://www.pepperdine.edu/",
  },
  {
    name: "Princeton University",
    town: "Princeton, NJ",
    region: "Northeast",
    sat: 1505,
    act: 34,
    gpa: 3.86,
    size: 4773,
    setting: "Suburban",
    type: "Private",
    link: "https://www.princeton.edu/",
  },
  {
    name: "Purdue University",
    town: "West Lafayette, IN",
    region: "Midwest",
    sat: 1315,
    act: 29,
    gpa: 3.79,
    size: 34920,
    setting: "Urban",
    type: "Public",
    link: "https://www.purdue.edu/",
  },
  {
    name: "Rice University",
    town: "Houston, TX",
    region: "South",
    sat: 1505,
    act: 34,
    gpa: 3.95,
    size: 4076,
    setting: "Urban",
    type: "Private",
    link: "https://www.rice.edu/",
  },
  {
    name: "Rutgers University",
    town: "New Brunswick, NJ",
    region: "Northeast",
    sat: 1300,
    act: 28,
    gpa: 3.3,
    size: 35844,
    setting: "Urban",
    type: "Public",
    link: "https://www.rutgers.edu/",
  },
  {
    name: "San Diego State University",
    town: "San Diego, CA",
    region: "West",
    sat: 1215,
    act: 26,
    gpa: 3.71,
    size: 31086,
    setting: "Urban",
    type: "Public",
    link: "https://www.sdsu.edu/",
  },
  {
    name: "Stanford University",
    town: "Stanford, CA",
    region: "West",
    sat: 1505,
    act: 34,
    gpa: 3.87,
    size: 6366,
    setting: "Suburban",
    type: "Private",
    link: "https://www.stanford.edu/",
  },
  {
    name: "Temple University",
    town: "Philadelphia, PA",
    region: "Northeast",
    sat: 1238,
    act: 27,
    gpa: 3.61,
    size: 27306,
    setting: "Urban",
    type: "Public",
    link: "https://www.temple.edu/",
  },
  {
    name: "Texas A&M University",
    town: "Brazos County, TX",
    region: "South",
    sat: 1275,
    act: 29,
    gpa: 3.68,
    size: 55568,
    setting: "Urban",
    type: "Public",
    link: "https://www.tamu.edu/",
  },
  {
    name: "The Ohio State University",
    town: "Columbus, OH",
    region: "Midwest",
    sat: 1355,
    act: 30,
    gpa: 3.83,
    size: 46984,
    setting: "Urban",
    type: "Public",
    link: "https://www.osu.edu/",
  },
  {
    name: "The Pennsylvania State University",
    town: "Centre County, PA",
    region: "Northeast",
    sat: 1265,
    act: 28,
    gpa: 3.61,
    size: 39809,
    setting: "Urban",
    type: "Public",
    link: "https://www.psu.edu/",
  },
  {
    name: "Tufts University",
    town: "Medford, MA",
    region: "Northeast",
    sat: 1465,
    act: 33,
    gpa: 3.91,
    size: 6114,
    setting: "Suburban",
    type: "Private",
    link: "https://www.tufts.edu/",
  },
  {
    name: "Tulane University",
    town: "New Orleans, LA",
    region: "South",
    sat: 1420,
    act: 32,
    gpa: 3.55,
    size: 7700,
    setting: "Urban",
    type: "Private",
    link: "https://tulane.edu/",
  },
  {
    name: "University of Arizona",
    town: "Tuscon, AZ",
    region: "West",
    sat: 1235,
    act: 25,
    gpa: 3.36,
    size: 36503,
    setting: "Urban",
    type: "Public",
    link: "https://www.arizona.edu/",
  },
  {
    name: "University of Arkansas",
    town: "Fayetteville, AR",
    region: "South",
    sat: 1210,
    act: 27,
    gpa: 3.7,
    size: 22825,
    setting: "Urban",
    type: "Public",
    link: "https://www.uark.edu/",
  },
  {
    name: "University of California Berkeley",
    town: "Berkeley, CA",
    region: "West",
    sat: 1415,
    act: 31,
    gpa: 3.85,
    size: 30980,
    setting: "Urban",
    type: "Public",
    link: "https://www.berkeley.edu/",
  },
  {
    name: "University of California-Davis",
    town: "Davis, CA",
    region: "West",
    sat: 1280,
    act: 28,
    gpa: 3.85,
    size: 31162,
    setting: "Urban",
    type: "Public",
    link: "https://www.ucdavis.edu/",
  },
  {
    name: "University of California Irvine",
    town: "Irvine, CA",
    region: "South",
    sat: 1310,
    act: 29,
    gpa: 3.86,
    size: 29638,
    setting: "Urban",
    type: "Public",
    link: "https://uci.edu/",
  },
  {
    name: "University of California, Los Angeles",
    town: "Los Angeles, CA",
    region: "West",
    sat: 1405,
    act: 31,
    gpa: 3.87,
    size: 31636,
    setting: "Urban",
    type: "Public",
    link: "https://www.ucla.edu/",
  },
  {
    name: "University of California Merced",
    town: "Merced, CA",
    region: "West",
    sat: 1080,
    act: 20,
    gpa: 3.51,
    size: 8276,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ucmerced.edu/",
  },
  {
    name: "University of California Riverside",
    town: "Riverside, CA",
    region: "West",
    sat: 1225,
    act: 27,
    gpa: 3.65,
    size: 22687,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ucr.edu/",
  },
  {
    name: "University of California San Diego",
    town: "San Diego, CA",
    region: "West",
    sat: 1360,
    act: 30,
    gpa: 3.84,
    size: 31842,
    setting: "Urban",
    type: "Public",
    link: "https://ucsd.edu/",
  },
  {
    name: "University of California Santa Barbara",
    town: "Santa Barbara, CA",
    region: "South",
    sat: 1355,
    act: 29,
    gpa: 3.85,
    size: 23196,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ucsb.edu/",
  },
  {
    name: "University of California Santa Cruz",
    town: "Santa Cruz, CA",
    region: "West",
    sat: 1285,
    act: 28,
    gpa: 3.47,
    size: 17207,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ucsc.edu/",
  },
  {
    name: "University of Central Florida",
    town: "Orange County, FL",
    region: "South",
    sat: 1259,
    act: 27,
    gpa: 3.81,
    size: 60075,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ucf.edu/",
  },
  {
    name: "University of Chicago",
    town: "Chicago, IL",
    region: "Midwest",
    sat: 1520,
    act: 34,
    gpa: 3.85,
    size: 6800,
    setting: "Urban",
    type: "Private",
    link: "https://www.uchicago.edu/",
  },
  {
    name: "University of Cincinnati",
    town: "Cincinnati, OH",
    region: "Midwest",
    sat: 1060,
    act: 21,
    gpa: 3.64,
    size: 28657,
    setting: "Urban",
    type: "Public",
    link: "https://www.uc.edu/",
  },
  {
    name: "University of Colorado Boulder",
    town: "Boulder, CO",
    region: "West",
    sat: 1253,
    act: 28,
    gpa: 3.72,
    size: 30300,
    setting: "Urban",
    type: "Public",
    link: "https://www.colorado.edu/",
  },
  {
    name: "University of Colorado Denver",
    town: "Denver, CO",
    region: "West",
    sat: 1120,
    act: 24,
    gpa: 3.44,
    size: 14995,
    setting: "Urban",
    type: "Public",
    link: "https://www.ucdenver.edu/",
  },
  {
    name: "University of Delaware",
    town: "Newark, DE",
    region: "South",
    sat: 1260,
    act: 28,
    gpa: 3.74,
    size: 18420,
    setting: "Suburban",
    type: "Public",
    link: "https://www.udel.edu/",
  },
  {
    name: "University of Florida",
    town: "Gainesville, FL",
    region: "South",
    sat: 1360,
    act: 30,
    gpa: 3.87,
    size: 34931,
    setting: "Suburban",
    type: "Public",
    link: "https://www.ufl.edu/",
  },
  {
    name: "University of Houston",
    town: "Houston, TX",
    region: "South",
    sat: 1225,
    act: 25,
    gpa: 3.54,
    size: 39165,
    setting: "Urban",
    type: "Public",
    link: "https://www.uh.edu/",
  },
  {
    name: "University of Illinois Chicago",
    town: "Chigago, IL",
    region: "Midwest",
    sat: 1120,
    act: 24,
    gpa: 3.33,
    size: 34199,
    setting: "Urban",
    type: "Public",
    link: "https://www.uic.edu/",
  },
  {
    name: "University of Illinois-Urbana Champaign",
    town: "Champaign, IL",
    region: "Midwest",
    sat: 1350,
    act: 29,
    gpa: 3.79,
    size: 33683,
    setting: "Urban",
    type: "Private",
    link: "https://illinois.edu/",
  },
  {
    name: "University of Iowa",
    town: "Johnson County, IA",
    region: "Midwest",
    sat: 1235,
    act: 26,
    gpa: 3.69,
    size: 22304,
    setting: "Suburban",
    type: "Public",
    link: "https://uiowa.edu/",
  },
  {
    name: "University of Kansas",
    town: "Lawrence, KA",
    region: "Midwest",
    sat: 1240,
    act: 26,
    gpa: 3.71,
    size: 19135,
    setting: "Urban",
    type: "Public",
    link: "https://ku.edu/",
  },
  {
    name: "University of Kentucky",
    town: "Lexington, KY",
    region: "South",
    sat: 1190,
    act: 26,
    gpa: 3.68,
    size: 22227,
    setting: "Urban",
    type: "Public",
    link: "https://www.uky.edu/",
  },
  {
    name: "University of Maryland Baltimore County",
    town: "Baltimore, MD",
    region: "South",
    sat: 1290,
    act: 27,
    gpa: 3.76,
    size: 10932,
    setting: "Suburban",
    type: "Public",
    link: "https://umbc.edu/",
  },
  {
    name: "University of Maryland College Park",
    town: "College Park, MD",
    region: "South",
    sat: 1380,
    act: 31,
    gpa: 3.86,
    size: 30875,
    setting: "Urban",
    type: "Public",
    link: "https://www.umd.edu/",
  },
  {
    name: "University of Massachusetts Amherst",
    town: "Amherst, MA",
    region: "Northeast",
    sat: 1290,
    act: 29,
    gpa: 3.79,
    size: 24233,
    setting: "Suburban",
    type: "Public",
    link: "https://www.umass.edu/",
  },
  {
    name: "University of Michigan, Ann Arbor",
    town: "Ann Arbor, MI",
    region: "Midwest",
    sat: 1435,
    act: 33,
    gpa: 3.84,
    size: 31329,
    setting: "Urban",
    type: "Public",
    link: "https://umich.edu/",
  },
  {
    name: "University of Minnesota, Twin Cities",
    town: "Minneapolis, MN",
    region: "Midwest",
    sat: 1351,
    act: 28,
    gpa: 3.75,
    size: 36061,
    setting: "Urban",
    type: "Public",
    link: "https://twin-cities.umn.edu/",
  },
  {
    name: "University of Mississippi",
    town: "Mississippi State, MS",
    region: "Midwest",
    sat: 1160,
    act: 25,
    gpa: 3.67,
    size: 16179,
    setting: "Suburban",
    type: "Public",
    link: "https://olemiss.edu/",
  },
  {
    name: "University of Missouri",
    town: "Columbia, MO",
    region: "Midwest",
    sat: 1190,
    act: 26,
    gpa: 3.61,
    size: 23396,
    setting: "Urban",
    type: "Public",
    link: "https://missouri.edu/",
  },
  {
    name: "University of Nebraska Lincoln",
    town: "Lincoln, NE",
    region: "Midwest",
    sat: 1240,
    act: 25,
    gpa: 3.59,
    size: 20286,
    setting: "Urban",
    type: "Public",
    link: "https://www.unl.edu/",
  },
  {
    name: "University of New Hampshire",
    town: "Durham, NH",
    region: "Northeast",
    sat: 1183,
    act: 25,
    gpa: 3.44,
    size: 16852,
    setting: "Urban",
    type: "Public",
    link: "https://www.unh.edu/",
  },
  {
    name: "University of New Mexico",
    town: "Albuquerque, NM",
    region: "West",
    sat: 1150,
    act: 22,
    gpa: 3.38,
    size: 16124,
    setting: "Urban",
    type: "Public",
    link: "http://www.unm.edu/",
  },
  {
    name: "University of North Carolina-Chapel Hill",
    town: "Chapel Hill, NC",
    region: "South",
    sat: 1395,
    act: 30,
    gpa: 3.87,
    size: 19399,
    setting: "Suburban",
    type: "Public",
    link: "https://www.unc.edu/",
  },
  {
    name: "University of Notre Dame",
    town: "Notre Dame, IN",
    region: "Midwest",
    sat: 1475,
    act: 34,
    gpa: 3.91,
    size: 8874,
    setting: "Suburban",
    type: "Private",
    link: "https://www.nd.edu/",
  },
  {
    name: "University of Oklahoma",
    town: "Norman, OK",
    region: "South",
    sat: 1210,
    act: 26,
    gpa: 3.68,
    size: 21383,
    setting: "Urban",
    type: "Public",
    link: "https://www.ou.edu/",
  },
  {
    name: "University of Oregon",
    town: "Eugene, OR",
    region: "West",
    sat: 1185,
    act: 25,
    gpa: 3.59,
    size: 18045,
    setting: "Urban",
    type: "Public",
    link: "https://www.uoregon.edu/",
  },
  {
    name: "University of Pennsylvania",
    town: "Philadelphia, PA",
    region: "Northeast",
    sat: 1500,
    act: 34,
    gpa: 3.86,
    size: 9872,
    setting: "Urban",
    type: "Private",
    link: "https://www.upenn.edu/",
  },
  {
    name: "University of Pittsburgh",
    town: "Pittsburgh, PA",
    region: "Northeast",
    sat: 1350,
    act: 31,
    gpa: 3.85,
    size: 19197,
    setting: "Urban",
    type: "Public",
    link: "https://www.pitt.edu/",
  },
  {
    name: "University of Rhode Island",
    town: "South Kingstown, RI",
    region: "South",
    sat: 1179,
    act: 25,
    gpa: 3.47,
    size: 14073,
    setting: "Duburban",
    type: "Public",
    link: "https://www.uri.edu/",
  },
  {
    name: "University of Rochester",
    town: "Rochester, NY",
    region: "Northeast",
    sat: 1420,
    act: 31,
    gpa: 3.8,
    size: 6521,
    setting: "Urban",
    type: "Private",
    link: "https://www.rochester.edu/",
  },
  {
    name: "University of South Carolina",
    town: "Columbia, SC",
    region: "South",
    sat: 1275,
    act: 28,
    gpa: 3.84,
    size: 27270,
    setting: "Urban",
    type: "Public",
    link: "https://sc.edu/",
  },
  {
    name: "University of South Florida",
    town: "Hillsborough County, FL",
    region: "South",
    sat: 1250,
    act: 27,
    gpa: 3.8,
    size: 38579,
    setting: "Urban",
    type: "Public",
    link: "https://www.usf.edu/",
  },
  {
    name: "University of Southern California",
    town: "Los Angeles, CA",
    region: "West",
    sat: 1440,
    act: 32,
    gpa: 3.79,
    size: 19606,
    setting: "Urban",
    type: "Private",
    link: "https://www.usc.edu/",
  },
  {
    name: "University of Tennessee Knoxville",
    town: "Knoxville, TN",
    region: "South",
    sat: 1240,
    act: 27,
    gpa: 3.8,
    size: 25254,
    setting: "Urban",
    type: "Public",
    link: "https://www.utk.edu/",
  },
  {
    name: "University of Texas at Dallas",
    town: "Dallas, TX",
    region: "South",
    sat: 1350,
    act: 30,
    gpa: 3.9,
    size: 21187,
    setting: "Urban",
    type: "Public",
    link: "https://www.utdallas.edu/",
  },
  {
    name: "University of Texas-Austin",
    town: "Austin, TX",
    region: "South",
    sat: 1355,
    act: 30,
    gpa: 3.8,
    size: 40048,
    setting: "Urban",
    type: "Public",
    link: "https://www.utexas.edu/",
  },
  {
    name: "University of Utah",
    town: "Salt Lake City, UT",
    region: "West",
    sat: 1262,
    act: 26,
    gpa: 3.68,
    size: 24643,
    setting: "Urban",
    type: "Public",
    link: "https://www.utah.edu/",
  },
  {
    name: "University of Vermont",
    town: "Burlington, VT",
    region: "Northeast",
    sat: 1270,
    act: 29,
    gpa: 3.66,
    size: 11136,
    setting: "Suburban",
    type: "Public",
    link: "https://www.uvm.edu/",
  },
  {
    name: "University of Virginia",
    town: "Charlottesville, VA",
    region: "South",
    sat: 1430,
    act: 32,
    gpa: 3.87,
    size: 17311,
    setting: "Suburban",
    type: "Public",
    link: "https://www.virginia.edu/",
  },
  {
    name: "University of Wyoming",
    town: "Laramie, WY",
    region: "West",
    sat: 1160,
    act: 25,
    gpa: 3.58,
    size: 9342,
    setting: "Suburban",
    type: "Public",
    link: "http://www.uwyo.edu/",
  },
  {
    name: "Vanderbilt University",
    town: "Nashville, TN",
    region: "South",
    sat: 1505,
    act: 34,
    gpa: 3.82,
    size: 7057,
    setting: "Urban",
    type: "Private",
    link: "https://www.vanderbilt.edu/",
  },
  {
    name: "Villanova University",
    town: "Villanova, PA",
    region: "Northeast",
    sat: 1395,
    act: 33,
    gpa: 3.84,
    size: 7037,
    setting: "Suburban",
    type: "Private",
    link: "https://www.villanova.edu/",
  },
  {
    name: "Virginia Commonwealth University",
    town: "Richmond, VA",
    region: "South",
    sat: 1165,
    act: 25,
    gpa: 3.62,
    size: 21707,
    setting: "Urban",
    type: "Public",
    link: "https://www.vcu.edu/",
  },
  {
    name: "Virginia Tech",
    town: "Blacksburg, VA",
    region: "South",
    sat: 1285,
    act: 28,
    gpa: 3.84,
    size: 30020,
    setting: "Suburban",
    type: "Public",
    link: "https://vt.edu/",
  },
  {
    name: "Wake Forest University",
    town: "Winston-Salem, NC",
    region: "South",
    sat: 1390,
    act: 31,
    gpa: 3.9,
    size: 5441,
    setting: "Suburban",
    type: "Private",
    link: "https://www.wfu.edu/",
  },
  {
    name: "Washington State University",
    town: "Pullman, WA",
    region: "West",
    sat: 1125,
    act: 23,
    gpa: 3.4,
    size: 25470,
    setting: "Urban",
    type: "Public",
    link: "https://wsu.edu/",
  },
  {
    name: "Washington University in St. Louis",
    town: "St. Louis, MO",
    region: "Midwest",
    sat: 1520,
    act: 34,
    gpa: 3.92,
    size: 7653,
    setting: "Urban",
    type: "Private",
    link: "https://wustl.edu/",
  },
  {
    name: "Yale University",
    town: "New Haven, CT",
    region: "Northeast",
    sat: 1515,
    act: 34,
    gpa: 3.95,
    size: 4703,
    setting: "Urban",
    type: "Private",
    link: "https://www.yale.edu/",
  },
];

for (let i = 0; i < collegeList.length; i++) {
  if (collegeList[i]["size"] < 7500) {
    collegeList[i]["sizeStr"] = "Small";
  } else if (collegeList[i]["size"] >= 20000) {
    collegeList[i]["sizeStr"] = "Large";
  } else {
    collegeList[i]["sizeStr"] = "Medium";
  }
  collegeList[i]["image"] = "school" + String(i + 1) + ".jpg"
}

export default collegeList;
